--Dirty read (RU)

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION

Select stars FROM HOTEL 
WHERE hotel_id = 120

Select stars FROM HOTEL 
WHERE hotel_id = 120

Select stars FROM HOTEL
WHERE hotel_id = 120
COMMIT